---
title: Pop Gym
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: info@popgym.org
description: Pop Gym, it's coming soon!
baseurl: ''
url: ''
twitter_username: popgymbk
facebook_username: popgymbk
instagram_username: popgymbk
markdown: kramdown
exclude:
- Gemfile
- Gemfile.lock
paginate: 8
paginate_path: updates/page:num
gems:
- jekyll-paginate
header_pages:
- about.md
- schedule.md
- mma.md
- deescalation.md
- contact.md
- fundraising.md
- resources.md
- store.md
