---
title: Pop Gym- Strength in Ourselves, Strength in our Communities
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: info@popgym.org
description: Free classes for self-defense, de-escalation, and more, all over New
  York City!
phone number: 573-POP-0143 (573-767-0143)
baseurl: ''
url: ''
twitter_username: popgymbk
facebook_username: popgymbk
instagram_username: popgymbk
markdown: kramdown
exclude:
- Gemfile
- Gemfile.lock
paginate: 8
paginate_path: updates/page:num
gems:
- jekyll-paginate
header_pages:
- about.md
- schedule.md
- programs.md
- contact.md
- zines.md
- resources.md
