---
title: Pop Gym
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: info@popgym.org
description: 'A blurb about a gym, it''s coming soon!

'
baseurl: ''
url: ''
twitter_username: popgymbk
facebook_username: popgymbk
instagram_username: popgymbk
markdown: kramdown
exclude:
- Gemfile
- Gemfile.lock
